language: bash

notifications:
  email: false

services:
  - docker

before_script:
  - docker build -t tango-test-build -f .travis/Dockerfile .
  - docker run --name tango-test-build -v `pwd`:/work -w=/work -dit tango-test-build
  - docker exec tango-test-build cmake .
  - docker exec tango-test-build make

script:
  - docker build -t tangocs/tango-test .

after_script:
  - docker rm -f tango-test-build

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag tangocs/tango-test tangocs/tango-test:${TRAVIS_BRANCH}

deploy:
  - provider: script
    script: docker push tangocs/tango-test:${TRAVIS_BRANCH}
    on:
      tags: true