dist: trusty
sudo: false

language: cpp

env:
  matrix:

notifications:
  email: false




before_install:
  - curl http://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
  - echo "deb https://dl.bintray.com/tango-controls/debian {distribution} {components}" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install varnish -y

before_script:
  - docker run --name mysql_db -e MYSQL_ROOT_PASSWORD=root -d tangocs/mysql:9.2.2 --sql-mode=""
  - CONTAINER=$(docker run --name tango_cs -e TANGO_HOST=127.0.0.1:10000 -e MYSQL_HOST=mysql_db:3306 -e MYSQL_USER=tango -e MYSQL_PASSWORD=tango -e MYSQL_DATABASE=tango --link mysql_db:mysql_db -d tangocs/tango-cs:latest)
  - IPADDR=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CONTAINER)
  - TANGO_HOST=${IPADDR}:10000
  - docker build --build-arg APP_UID=$(id -u) --build-arg APP_GID=$(id -g) -t cpp_tango .travis/${OS_TYPE}
  - docker run --name cpp_tango -e TANGO_HOST=${TANGO_HOST} -e BINTRAY_USER_NAME=tango-ci -e BINTRAY_API_KEY=${CI_BINTRAY_API_KEY} -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} --link tango_cs:tango_cs -v `pwd`:/home/tango/src -v `pwd`/idl:/home/tango/idl -v `pwd`/cppzmq:/home/tango/cppzmq -v `pwd`/coveralls-cmake:/home/tango/coveralls-cmake -v `pwd`/build-wrapper-linux-x86:/home/tango/build-wrapper-linux-x86 -dit cpp_tango
  - .travis/install_tango_idl.sh
  - .travis/install_cppzmq.sh
#work around gcov ignored by sonar
  - sudo mkdir /home/tango && sudo mkdir /home/tango/src && sudo mount --bind `pwd` /home/tango/src

script:
  - .travis/${OS_TYPE}/run.sh
  - .travis/test.sh COVERALLS=OFF

after_success:
  - test ${SONAR_SCANNER} = "ON" && .travis/sonar.sh

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true

after-script:
  - docker stop cpp_tango
  - docker rm cpp_tango
  - docker stop tango_cs
  - docker rm tango_cs
  - docker stop mysql_db
- docker rm mysql_db
